name: Test Docusaurus Build

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  build-test:
    name: Test Docusaurus Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: docs/node_modules
          key: docs-${{ hashFiles('docs/bun.lock') }}
          restore-keys: docs-

      - name: Install and Build
        run: |
          bun install --frozen-lockfile
          bun run build
