name: Test Docusaurus Build

on:
  pull_request:
    branches: [ "develop", "main" ]
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: ${{ runner.os }}-docs-

      - name: Install Dependencies
        working-directory: docs
        run: npm ci

      - name: Build Docusaurus
        working-directory: docs
        run: npm run build
